[package]
name = "leeway"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.103"
chrono = "0.4.45"
crossterm = "0.29.0"
ratatui = "0.30.2"
rusqlite = { version = "0.40.1", features = ["bundled"] }
rusqlite_migration = "2.6.0"
thiserror = "2.0.18"
uuid = { version = "1.23.4", features = ["v4"] }
